[package]
name = "raytrace"
version = "0.1.0"
authors = ["DarkAce65 <tvdood99@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33"
image = "0.22"
minifb = "0.13"
nalgebra = "0.19"
num-traits = "0.2"
