[package]
name = "raytracing"
version = "0.1.0"
authors = ["DarkAce65 <tvdood99@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.22"
